let suggestion = [
    "Channel",
    "Coding Lab",
    "Code with pranav",
    "Youtube",
    "Instagram",
    "Linkedin",
    "Blogger",
    "Bollywood",
    "Vlogger",
    "vehicles",
    "Facebook",
    "Freelancer",
    "Frontend developer",
    "Designer",
    "Developer",
    "Web developer",
    "Development",
    "Login form in html and css",
    "How to learn HTML and CSS",
    "How to learn Javascript ",
    "How to become freelancer",
    "How to become web designer",
    "How to start gaming channel",
    "how to start youtube channel",
    "What does html stahds for ? ",
    "What does html stahds for ?"
]
